In [ ]:
import numpy as np

In [ ]:
#3.1 (a) To get help on the add() function
import numpy as np
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

In [ ]:
#3.1 (a) To get help on the add() function
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [ ]:
#(b) To test whether none of the elements of a given array is zero.
import numpy as np
arr = np.array([1, 2, 3, 4])
print("\nAll elements are non-zero:", np.all(arr))



All elements are non-zero: True


In [ ]:
#(c) To create an element-wise comparison (greater, greater_equal,
#less and less_equal,equal, equal within a tolerance) of two given arrays.
#greater
a = np.array([10, 20, 30])
b = np.array([15, 20, 25])

print("Greater:", np.greater(a, b))            # [False False  True]
print("Greater Equal:", np.greater_equal(a, b))# [False  True  True]
print("Less:", np.less(a, b))                  # [ True False False]
print("Less Equal:", np.less_equal(a, b))      # [ True  True False]
print("Equal:", np.equal(a, b))                # [False  True False]

# Check if arrays are almost equal (within tolerance)
c = np.array([1.00001, 2.00001])
d = np.array([1.00002, 2.00002])
print("Allclose:", np.allclose(c, d))          # True (within default tolerance)

Greater: [False False  True]
Greater Equal: [False  True  True]
Less: [ True False False]
Less Equal: [ True  True False]
Equal: [False  True False]
Allclose: True


In [ ]:
#zeros
import numpy as np
print("\nZeros:", np.zeros((3,2)))


Zeros: [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
#ones
import numpy as np
print("Ones:", np.ones((2,3)))

Ones: [[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#linspace
import numpy as np
print("Linspace:", np.linspace(100, 1500, 8))

Linspace: [ 100.  300.  500.  700.  900. 1100. 1300. 1500.]


In [ ]:
#tolist
import numpy as np
print("Convert array to list:", a.tolist())

Convert array to list: [10, 20, 30]


In [6]:
#3.2 NumPy Program Using Methods
#🔹 a. Extract numbers from array which are less and greater than a specified number
import numpy as np
arr = np.array([5, 15, 25, 35, 45])

# Extract numbers greater than 20
print("Greater than 20:", arr[arr > 20])  # [25 35 45]
print(arr)
# Extract numbers less than 30
print("Less than 30:", arr[arr < 30])     # [5 15 25]
print(arr)

Greater than 20: [25 35 45]
[ 5 15 25 35 45]
Less than 30: [ 5 15 25]
[ 5 15 25 35 45]


In [7]:
#Find indices of max and min numbers along a given axis
arr2d = np.array([[10, 20, 30], [5, 25, 15]])

# Index of max along axis 0 (column-wise)
print("Argmax (axis=0):", np.argmax(arr2d, axis=0))  # [0 1 0]

# Index of min along axis 1 (row-wise)
print("Argmin (axis=1):", np.argmin(arr2d, axis=1))  # [0 0]


Argmax (axis=0): [0 1 0]
Argmin (axis=1): [0 0]


In [ ]:
#Repr,Bincount and Unique
import numpy as np
a = np.array([1, 2, 1, 3, 2, 1, 4])
print("Repr:", repr(a))
print("Bincount:", np.bincount(a))
print("Unique values:", np.unique(a))


Repr: array([1, 2, 1, 3, 2, 1, 4])
Bincount: [0 3 2 1 1]
Unique values: [1 2 3 4]
